# Generated by Django 6.0 on 2026-01-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0006_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='note_type',
            field=models.CharField(default='clue', max_length=20),
        ),
    ]
