# Generated by Django 4.2.7 on 2026-01-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0007_notes_note_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pro_pic',
        ),
    ]
